version: '3.8'

services:
  unified:
    build: 
      context: .
      dockerfile: docker/unified/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PIP_VERSION=24.0
      - PYTHONPATH=/app
      - PIP_NO_CACHE_DIR=1
      - PYTHONUNBUFFERED=1
      - FLASK_APP=src/server.py
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    restart: unless-stopped
    volumes:
      - ./src:/app/src  # Live code reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://unified:8000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    restart: unless-stopped
    depends_on:
      unified:
        condition: service